name: sim_gui_app
channels:
    - conda-forge
    - cantera
dependencies:
    - python
    - pandas
    - numpy
    - scipy
    - matplotlib
    - dash
    - dash-bootstrap-components
    - plotly
    - glom
    - redis
    - pandarallel
    - tqdm
    - pip
    - openpyxl
    - cantera
    - pip:
        - gunicorn
        - dash-extensions
        - flask-caching
        - jsonpickle
        - jsonnet-binary
        - git+https://github.com/ZBT-Tools/data-transfer.git@master#egg=data_transfer


